---
include:
  - board: nice_nano_v2
    shield: corne_left
    # snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_STUDIO=y
    # artifact-name: corne_left_with_studio
  - board: nice_nano_v2
    shield: corne_right
  - board: nice_nano_v2
    shield: settings_reset
